/** Amal nomlari — klient va server uchun umumiy (Prisma importsiz) */
export const ACTION_LABELS: Record<string, string> = {
  LOGIN_OTP: "Kirish (OTP)",
  LOGIN_PASSWORD: "Kirish (parol)",
  LOGIN_FAIL: "Kirish muvaffaqiyatsiz",
  CLINIC_CREATE: "Klinika yaratildi",
  CLINIC_UPDATE: "Klinika ma'lumoti o'zgartirildi",
  CLINIC_VERIFY: "Klinika tasdiqlandi",
  CLINIC_TIER: "Tarif o'zgartirildi",
  CLINIC_PASSWORD_RESET: "Klinika paroli yangilandi",
  SERVICES_UPDATE: "Xizmatlar/narxlar o'zgartirildi",
  DOCTOR_CREATE: "Shifokor qo'shildi",
  DOCTOR_UPDATE: "Shifokor o'zgartirildi",
  DOCTOR_DELETE: "Shifokor o'chirildi",
  DOCTOR_VERIFY: "Shifokor hujjati tekshirildi",
  CLINIC_DELETE: "Klinika o'chirildi",
  USER_BLOCK: "Foydalanuvchi bloklandi",
  USER_DELETE: "Foydalanuvchi o'chirildi",
  SERVICE_CATALOG_EDIT: "Xizmatlar katalogi o'zgartirildi",
  USER_EDIT: "Foydalanuvchi tahrirlandi",
  APT_CREATE: "Yozuv so'rovi yaratildi",
  APT_CONFIRM: "Yozuv tasdiqlandi",
  APT_REJECT: "Yozuv rad etildi",
  APT_ALT: "Muqobil vaqt taklif qilindi",
  APT_CANCEL: "Yozuv bekor qilindi",
  APT_RESCHEDULE: "Bemor vaqtni o'zgartirdi",
  APT_ARRIVED: "Bemor keldi",
  APT_NO_SHOW: "Bemor kelmadi",
  APT_DONE: "Yozuv yakunlandi",
  APT_CHECKIN: "Bemor check-in qildi",
  REVIEW_CREATE: "Sharh yozildi",
  REVIEW_APPROVE: "Sharh tasdiqlandi",
  REVIEW_REJECT: "Sharh rad etildi",
  REVIEW_REPLY: "Sharhga javob yozildi",
  PROMO_CREATE: "Promo slot yaratildi",
  PROMO_END: "Promo slot tugatildi",
  PHOTO_UPLOAD: "Rasm yuklandi",
  TG_LINK: "Telegram ulandi",
  TG_UNLINK: "Telegram uzildi",
  PROFILE_UPDATE: "Profil o'zgartirildi",
  PHONE_CHANGE: "Telefon raqami almashtirildi",
  SERVICE_CUSTOM_ADD: "Maxsus xizmat qo'shildi",
  SERVICE_CUSTOM_DEL: "Maxsus xizmat o'chirildi",
};
